# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import utils.files_preparing


class Migration(migrations.Migration):

    dependencies = [
        ('football_object', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballobject',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='footballobject',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='footballobject',
            name='user',
        ),
        migrations.AddField(
            model_name='footballobject',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballobject',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='footballobject',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
