# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import utils.files_preparing


class Migration(migrations.Migration):

    dependencies = [
        ('football_object', '0002_auto_20161002_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
