# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_object', '0003_footballclub_footballcountry_footballer'),
        ('records', '0007_auto_20161011_0507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FootballObject',
        ),
        migrations.AddField(
            model_name='footballer',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_object.FootballClub'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_object.FootballCountry'),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_object.FootballCountry'),
        ),
    ]
