# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.files_preparing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SectionArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=120)),
                ('article_description', models.TextField(max_length=240)),
                ('article_text', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('article_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlesSection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
