# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.TextField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('article_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlesSection')),
            ],
        ),
    ]
