# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.TextField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.TextField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('album_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.GallerySection')),
            ],
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='photo_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.SectionAlbum'),
        ),
    ]
