# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_sectionalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.TextField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.SectionAlbum')),
            ],
        ),
    ]
