# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import utils.files_preparing


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_albumphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysection',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 9, 21, 7, 5, 278927, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 9, 21, 7, 22, 98267, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
