# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import utils.files_preparing


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20161009_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.files_preparing.upload_location),
        ),
    ]
