# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.files_preparing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_object', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=utils.files_preparing.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_object.FootballCountry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
