# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 10:18
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fhuser',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fhuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
