# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161015_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_object.FootballCountry'),
        ),
        migrations.AlterField(
            model_name='fhuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
