# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161015_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhuser',
            name='is_admin',
        ),
    ]
