# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.files_preparing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_coef', models.FloatField()),
                ('draw_coef', models.FloatField()),
                ('guest_coef', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=80)),
                ('league_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.files_preparing.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.TextField(blank=True, null=True)),
                ('home_goals', models.IntegerField(default=0)),
                ('guest_goals', models.IntegerField(default=0)),
                ('match_time', models.DateTimeField()),
                ('match_type', models.IntegerField(choices=[(0, 'simple'), (1, 'continental club match'), (2, 'world club match'), (3, 'continental national teams match'), (4, 'world national teams match'), (5, 'special')], default=0)),
                ('match_result', models.IntegerField(choices=[(-1, 'No played'), (0, 'Home win'), (1, 'Draw'), (2, 'Guest win')], default=-1)),
                ('match_bonus', models.FloatField(blank=True, null=True)),
                ('match_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchBetFromUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bet', models.PositiveSmallIntegerField(choices=[(0, 'home win'), (1, 'draw'), (2, 'guest win')], default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Match')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('season_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.League')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Season')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=80)),
                ('is_current', models.BooleanField(default=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('stage_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('must_be_checked', models.BooleanField(default=True)),
                ('match_1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stagebet_match1_stage', to='bettournament.Match')),
                ('match_2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stagebet_match2_stage', to='bettournament.Match')),
                ('match_3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stagebet_match3_stage', to='bettournament.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
                ('team_short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.files_preparing.upload_location)),
                ('team_league', models.ManyToManyField(to='bettournament.Season')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeasonResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.SmallIntegerField(default=0)),
                ('games', models.SmallIntegerField(default=0)),
                ('goals', models.SmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bettournament.SeasonGroup')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bettournament.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UsersResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('result_match1', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usersresult_match1_result', to='bettournament.MatchBetFromUser')),
                ('result_match2', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usersresult_match2_result', to='bettournament.MatchBetFromUser')),
                ('result_match3', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usersresult_match3_result', to='bettournament.MatchBetFromUser')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.StageBet')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest_team', to='bettournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='bettournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.SeasonStage'),
        ),
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.LeagueType'),
        ),
        migrations.AddField(
            model_name='coefficient',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Match'),
        ),
    ]
