# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_coef', models.FloatField()),
                ('draw_coef', models.FloatField()),
                ('guest_coef', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=80)),
                ('league_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('match_type', models.IntegerField(choices=[(0, 'simple'), (1, 'continental club match'), (2, 'world club match'), (3, 'continental national teams match'), (4, 'world national teams match'), (5, 'special')], default=0)),
                ('match_bonus', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchBetFromUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bet', models.PositiveSmallIntegerField(choices=[(0, 'home win'), (1, 'draw'), (2, 'guest win')], default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Match')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
                ('team_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.League')),
            ],
        ),
        migrations.CreateModel(
            name='UsersResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bettournament.MatchBetFromUser')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest_team', to='bettournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='bettournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettournament.League'),
        ),
        migrations.AddField(
            model_name='coefficient',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Match'),
        ),
    ]
