# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bettournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_coef', models.FloatField()),
                ('draw_coef', models.FloatField()),
                ('guest_coef', models.FloatField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bettournament.Match')),
            ],
        ),
        migrations.RenameModel(
            old_name='UsersResults',
            new_name='UsersResult',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matchbetfromuser',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='matchbetfromuser',
            name='guest_win',
        ),
        migrations.RemoveField(
            model_name='matchbetfromuser',
            name='home_win',
        ),
        migrations.RemoveField(
            model_name='matchpreview',
            name='match_bet_coeffs',
        ),
        migrations.AddField(
            model_name='matchbetfromuser',
            name='user_bet',
            field=models.PositiveSmallIntegerField(choices=[(0, 'home win'), (1, 'draw'), (2, 'guest win')], default=1),
        ),
        migrations.DeleteModel(
            name='Coefficients',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
