# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bettournament', '0002_auto_20161001_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bettournament.League'),
            preserve_default=False,
        ),
    ]
