# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20160924_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordgroup',
            name='slug',
            field=models.SlugField(default='transfers', unique=True),
            preserve_default=False,
        ),
    ]
