# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_recordgroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(default='ronaldo', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtable',
            name='slug',
            field=models.SlugField(default='transfers', unique=True),
            preserve_default=False,
        ),
    ]
