# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20160924_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_value',
            field=models.IntegerField(),
        ),
    ]
