# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20161002_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-record_value']},
        ),
    ]
