# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('records', '0006_auto_20161009_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_owner',
        ),
        migrations.AddField(
            model_name='record',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='owner_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
